Repository TeamZOOC/ZOOC-iOS, pull requests merged in 2023-03, with the labels that each got.

#96 [Feat] #95 - 소셜로그인 플로우 수정
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/Common/Model/User.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingAppleSocialLoginRequest.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingFamilyResult.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingJWTTokenResult.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingRegisterPetRequest.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingRegisterUserRequest.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingResult.swift
  ZOOC/ZOOC/Network/Base/APIConstants.swift
  ZOOC/ZOOC/Network/Home/HomeAPI.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingAPI.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingService.swift
  ZOOC/ZOOC/Network/Record/RecordAPI.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
Labels: 🐶 석우, ✨ Feature

#97 [Feat] #94 - 푸시알림 구현하기
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ZOOC/ZOOC/Application/AppDelegate.swift
  ZOOC/ZOOC/Application/Info.plist
  ZOOC/ZOOC/Data/Common/APIModel/VoidResult.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingJoinFamilyRequest.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingJoinUserResult.swift
  ZOOC/ZOOC/Data/User.swift
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/GoogleService-Info.plist
  ZOOC/ZOOC/Network/Base/APIConstants.swift
  ZOOC/ZOOC/Network/Base/BaseAPI.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingAPI.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingService.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingCompleteProfileViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingJoinFamilyCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingJoinFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift
  ZOOC/ZOOC/ZOOC.entitlements
Labels: 🐶 석우, ✨ Feature

#104 [Feat] #98 - 홈뷰 게시물 유무에 따른 분기 처리 및 화면 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Global/Constant/Image.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeGuideView.swift
  ZOOC/ZOOC/Resource/Assets.xcassets/Graphics/graphics_8.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/Graphics/graphics_8.imageset/Group 48095940@2x.png
  ZOOC/ZOOC/Resource/Assets.xcassets/Graphics/graphics_8.imageset/Group 48095940@3x.png
  ZOOC/ZOOC/Resource/Assets.xcassets/Graphics/graphics_8.imageset/graphics_8.png
  ZOOC/ZOOC/Resource/Assets.xcassets/arrow.down.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/arrow.down.imageset/Group 48095938@2x.png
  ZOOC/ZOOC/Resource/Assets.xcassets/arrow.down.imageset/Group 48095938@3x.png
  ZOOC/ZOOC/Resource/Assets.xcassets/arrow.down.imageset/arrow.down.png
Labels: 🐶 석우, ✨ Feature

#106 [Feat] #105 - 온보딩 플로우 정리
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/My/Model/MyPetRegisterViewModel.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingMakeFamilyResult.swift
  ZOOC/ZOOC/Data/Onboarding/Model/OnboardingPetRegisterViewModel.swift
  ZOOC/ZOOC/Global/Constant/Image.swift
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/My/MyAPI.swift
  ZOOC/ZOOC/Network/My/MyService.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingAPI.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingService.swift
  ZOOC/ZOOC/Network/Record/RecordAPI.swift
  ZOOC/ZOOC/Presentation/Base/BaseViewController.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordRegisterCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordRegisterFourCollectionViewCell.swift
  ZOOC/ZOOC/Resource/Assets.xcassets/Default/default_profile_pet.imageset/default__profile_pet.png
  ZOOC/ZOOC/Resource/Assets.xcassets/camera.circle.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/camera.circle.imageset/Group 48095810@2x 1.png
  ZOOC/ZOOC/Resource/Assets.xcassets/camera.circle.imageset/Group 48095810@2x.png
  ZOOC/ZOOC/Resource/Assets.xcassets/camera.circle.imageset/Group 48095810@3x.png
  ZOOC/ZOOC/Resource/Assets.xcassets/camera.circle.small.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/camera.circle.small.imageset/camera.circle.small.png
Labels: 🐶 석우, ✨ Feature

#111 [Feat] #110 - 로그아웃 FCM API 연동
  ZOOC/ZOOC/Application/SceneDelegate.swift
  ZOOC/ZOOC/Data/User.swift
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/My/MyAPI.swift
  ZOOC/ZOOC/Network/My/MyService.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift
Labels: 🐶 석우, ✨ Feature

#114 [Fix] #112 Foreground 일때 알림 안오는 오류 해결
  ZOOC/ZOOC/Application/AppDelegate.swift
Labels: 🐶 석우, 🔨 Fix

#109 [Refactor] #108 - 온보딩 UI 변경 사항 반영
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Application/Info.plist
  ZOOC/ZOOC/Global/Constant/Image.swift
  ZOOC/ZOOC/Global/Extension/UILabel+.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingAgreementTableHeaderView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingChooseFamilyRoleViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingJoinFamilyCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingJoinFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterProfileImageViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingAgreementView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingBaseView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingChooseFamilyRoleView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingCompleteProfileView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteCompletedFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingJoinFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingLoginView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingReInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterPetView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterProfileImageView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingWelcomeView.swift
  ZOOC/ZOOC/Resource/Assets.xcassets/Graphics/graphics_9.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/Graphics/graphics_9.imageset/Group 48095887.png
  ZOOC/ZOOC/Resource/Assets.xcassets/Graphics/graphics_9.imageset/Group 48095887@2x.png
  ZOOC/ZOOC/Resource/Assets.xcassets/Graphics/graphics_9.imageset/Group 48095887@3x.png
Labels: 🐼 희재, ⚒️ Refactor
