Repository TeamZOOC/ZOOC-iOS, pull requests merged in 2023-01, with the labels that each got.

#8 [Feat] #6 - 마이페이지 UI 구현
  ZOOC/MemberModel.swift
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Global/Constant/Image.swift
  ZOOC/ZOOC/Presentation/My/Cell/FamilyCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MemberCollectionHeaderView.swift
  ZOOC/ZOOC/Presentation/My/Cell/PetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/SettingMenuModel.swift
  ZOOC/ZOOC/Presentation/My/Cell/SettingMenuTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/My/FamilyCollectionView.swift
  ZOOC/ZOOC/Presentation/My/View/MyView.swift
  ZOOC/ZOOC/Presentation/My/View/PetCollectionView.swift
  ZOOC/ZOOC/Presentation/My/View/ProfileView.swift
  ZOOC/ZOOC/Presentation/My/View/SettingMenuTableView.swift
  ZOOC/ZOOC/Resource/Assets.xcassets/profile_image.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/profile_image.imageset/Ellipse 1316.png
  ZOOC/ZOOC/Resource/Assets.xcassets/profile_memberImage.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/profile_memberImage.imageset/mypage_profile.png
Labels: 🐼 희재, ✨ Feature

#11 [Feat] #5 - 온보딩 - 미션기록뷰 UI 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ZOOC/ZOOC/Application/SceneDelegate.swift
  ZOOC/ZOOC/Data/Home/APIModel/Empty.md
  ZOOC/ZOOC/Data/My/APIModel/Empty.md
  ZOOC/ZOOC/Data/My/Model/Empty.md
  ZOOC/ZOOC/Data/Onboarding/APIModel/Empty.md
  ZOOC/ZOOC/Data/Onboarding/Model/Empty.md
  ZOOC/ZOOC/Data/Record/APIModel/Empty.md
  ZOOC/ZOOC/Data/Record/Model/Empty.md
  ZOOC/ZOOC/Global/Constant/Image.swift
  ZOOC/ZOOC/Global/Extension/UIColor+.swift
  ZOOC/ZOOC/Global/Extension/UIView+.swift
  ZOOC/ZOOC/Presentation/Base/ZoocTabBarController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/Home/View/Empty.md
  ZOOC/ZOOC/Presentation/My/Cell/SettingMenuModel.swift
  ZOOC/ZOOC/Presentation/My/Cell/SettingMenuTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/View/Empty.md
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnBoardingMissionControllerHomeViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingGuideCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingMissionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/View/Empty.md
  ZOOC/ZOOC/Resource/Assets.xcassets/gallery.imageset/gallery.png
  ZOOC/ZOOC/Resource/Assets.xcassets/home.imageset/home.png
  ZOOC/ZOOC/Resource/Assets.xcassets/onboarding_mission.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/onboarding_mission.imageset/first_mission.png
  ZOOC/ZOOC/Resource/Assets.xcassets/person.imageset/person.png
Labels: 🐶 석우, ✨ Feature

#10 [Feat] #7 - 가족초대 UI 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ZOOC/ZOOC/Presentation/My/Controller/MyFamilyInviteViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyInviteCompleteViewController.swift
Labels: 🐰 윤선, ✨ Feature

#14 Feat/#9
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ZOOC/ZOOC/Data/My/Model/MemberModel.swift
  ZOOC/ZOOC/Global/Extension/UINavigationController+.swift
  ZOOC/ZOOC/Presentation/Base/ZoocTabBarController.swift
  ZOOC/ZOOC/Presentation/My/Cell/AppInformationModel.swift
  ZOOC/ZOOC/Presentation/My/Cell/AppInformationTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/SettingMenuModel.swift
  ZOOC/ZOOC/Presentation/My/Cell/SettingMenuTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Controller/AppInformationViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/EditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/My/MyProfileModel.swift
  ZOOC/ZOOC/Presentation/My/View/AppInformationView.swift
  ZOOC/ZOOC/Presentation/My/View/EditProfileAlertView.swift
  ZOOC/ZOOC/Presentation/My/View/EditProfileView.swift
  ZOOC/ZOOC/Presentation/My/View/FamilyCollectionView.swift
  ZOOC/ZOOC/Presentation/My/View/MyAlertViewController.swift
  ZOOC/ZOOC/Presentation/My/View/PetCollectionView.swift
  ZOOC/ZOOC/Presentation/My/View/ProfileView.swift
  ZOOC/ZOOC/Presentation/My/View/SettingMenuTableView.swift
  ZOOC/ZOOC/Resource/Assets.xcassets/하지만.imageset/Contents.json
Labels: 🐼 희재, ✨ Feature

#24 [Feat] #20 - 온보딩 UI 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Application/SceneDelegate.swift
  ZOOC/ZOOC/Data/Onboarding/Model/OnboardingAgreementModel.swift
  ZOOC/ZOOC/Data/Onboarding/OnboardingPetRegisterModel.swift
  ZOOC/ZOOC/Global/Constant/Image.swift
  ZOOC/ZOOC/Global/Extension/UIButton+.swift
  ZOOC/ZOOC/Global/Extension/UILabel+.swift
  ZOOC/ZOOC/Global/Extension/UITableViewHeaderFooterView+.swift
  ZOOC/ZOOC/Presentation/My/Controller/AppInformationViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/EditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/View/EditProfileView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingAgreementTableHeaderView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingAgreementTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableFooterView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingChooseFamilyRoleViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingCompleteProfileViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingReInviteFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterProfileImageViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingSecondaryCompleteProfileViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingSecondaryWelcomeViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingWelcomeViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingAgreementView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingChooseFamilyRoleView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingCompleteProfileView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteCompletedFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingLoginView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateCompletedView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingReInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterPetView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterProfileImageView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingSecondaryCompleteProfileView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingSecondaryWelcomeView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingWelcomeView.swift
Labels: 🐼 희재, ✨ Feature

#26 [Feat] #13 - 기록하기 뷰 UI 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Application/SceneDelegate.swift
  ZOOC/ZOOC/Data/Record/Model/Empty.md
  ZOOC/ZOOC/Data/Record/Model/RecordModel.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordAlertViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
Labels: 🐰 윤선, ✨ Feature

#27 [Feat] #21 - 등록 플로우 UI 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/Record/Model/RecordRegisterModel.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordCompleteViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift
  ZOOC/ZOOC/Presentation/Record/View/Empty.md
  ZOOC/ZOOC/Presentation/Record/View/RecordRegisterCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordRegisterFourCollectionViewCell.swift
Labels: 🐰 윤선, ✨ Feature

#28 [Feat] #23 - 상세뷰 UI 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Application/SceneDelegate.swift
  ZOOC/ZOOC/Data/Home/Model/HomeDetailArchiveModel.swift
  ZOOC/ZOOC/Global/Constant/Image.swift
  ZOOC/ZOOC/Global/Extension/UITextField+.swift
  ZOOC/ZOOC/Global/Extension/UIViewController+.swift
  ZOOC/ZOOC/Presentation/Base/BaseViewController.swift
  ZOOC/ZOOC/Presentation/Base/ZoocTabBarController.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeCommentCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomePetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeArchiveIndicatorView.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeDetailArchiveCommentTextField.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordAlertViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordCompleteViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
  ZOOC/ZOOC/Resource/Assets.xcassets/Mock/mock_hidi.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/Mock/mock_hidi.imageset/hidi.jpg
  ZOOC/ZOOC/Resource/Assets.xcassets/Mock/mock_seokwoo.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/Mock/mock_seokwoo.imageset/seokwoo.jpg
  ZOOC/ZOOC/Resource/Assets.xcassets/Mock/mock_yunsun.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/Mock/mock_yunsun.imageset/yunsun.jpg
Labels: 🐶 석우, ✨ Feature

#33 [Feat] #29 - 홈뷰 서버 통신
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/Home/APIModel/HomeArchiveResult.swift
  ZOOC/ZOOC/Data/Home/APIModel/HomeMissionResult.swift
  ZOOC/ZOOC/Data/Home/APIModel/HomePetResult.swift
  ZOOC/ZOOC/Data/User.swift
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/Base/BaseAPI.swift
  ZOOC/ZOOC/Network/Home/HomeAPI.swift
  ZOOC/ZOOC/Network/Home/HomeService.swift
  ZOOC/ZOOC/Presentation/Base/BaseViewController.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveGridCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListWriterCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeCommentCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomePetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeDetailArchiveCommentTextField.swift
Labels: 🐶 석우, ✨ Feature

#35 [Feat] 상세뷰 서버통신 #34
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/Common/APIModel/RecordResult.swift
  ZOOC/ZOOC/Data/Common/Model/Empty.md
  ZOOC/ZOOC/Data/Common/Model/User.swift
  ZOOC/ZOOC/Data/Home/APIModel/HomeArchiveResult.swift
  ZOOC/ZOOC/Data/Home/APIModel/HomeDetailArchiveResult.swift
  ZOOC/ZOOC/Global/Extension/UIImage+.swift
  ZOOC/ZOOC/Network/Home/HomeAPI.swift
  ZOOC/ZOOC/Network/Home/HomeService.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeCommentCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
Labels: 🐶 석우, ✨ Feature

#37 [Feat] #36 -온보딩 화면 전환 연결
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ZOOC/ZOOC/Application/SceneDelegate.swift
  ZOOC/ZOOC/Data/Common/Model/User.swift
  ZOOC/ZOOC/Presentation/Base/ZoocTabBarController.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeGuideCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeMissionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeGuideViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingCompleteProfileViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingWelcomeViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingCompleteProfileView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingWelcomeView.swift
Labels: 🐶 석우, ✨ Feature

#39 [Feat]#38 - 기록뷰 서버통신 구현 (멀티파트 제외 )
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/Record/APIModel/Empty.md
  ZOOC/ZOOC/Data/Record/APIModel/RecordPetResult.swift
  ZOOC/ZOOC/Data/Record/Model/RecordRegisterModel.swift
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/Base/APIConstants.swift
  ZOOC/ZOOC/Network/Base/BaseTargetType.swift
  ZOOC/ZOOC/Network/Base/SimpleResponse.swift
  ZOOC/ZOOC/Network/Record/RecordAPI.swift
  ZOOC/ZOOC/Network/Record/RecordService.swift
  ZOOC/ZOOC/Network/Record/RescordAPI.swift
  ZOOC/ZOOC/Presentation/Practice/PracticeViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordRegisterCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordRegisterFourCollectionViewCell.swift
  ZOOC/ZOOC/Resource/Lottie/loading.json
Labels: 🐶 석우, ✨ Feature

#40 [Feat]#31 - 마이페이지뷰 서버 통신
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/Home/APIModel/HomeNoticeResult.swift
  ZOOC/ZOOC/Data/Home/Model/HomeNoticeModel.swift
  ZOOC/ZOOC/Data/My/APIModel/MyResult.swift
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/Base/APIConstants.swift
  ZOOC/ZOOC/Network/Base/BaseAPI.swift
  ZOOC/ZOOC/Network/Home/HomeAPI.swift
  ZOOC/ZOOC/Network/Home/HomeService.swift
  ZOOC/ZOOC/Network/My/MyAPI.swift
  ZOOC/ZOOC/Network/My/MyService.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeNoticeTableViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeNoticeViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeNoticeView.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilyCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyProfileSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyDeleteAccountAlertViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyEditProfileView.swift
Labels: 🐼 희재, ✨ Feature

#44 [Feat] #41 - 온보딩 서버통신 및 소셜로그인
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Application/AppDelegate.swift
  ZOOC/ZOOC/Application/Info.plist
  ZOOC/ZOOC/Application/SceneDelegate.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingRegisterUserRequestDto.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingResult.swift
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/Base/APIConstants.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingAPI.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingService.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateViewController.swift
Labels: 🐼 희재, ✨ Feature

#47 [Feat] #42 - 홈뷰 서버통신, 기록하기 멀티파트 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Application/SceneDelegate.swift
  ZOOC/ZOOC/Data/My/APIModel/Empty.md
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Global/Extension/Encodable+.swift
  ZOOC/ZOOC/Network/Home/HomeAPI.swift
  ZOOC/ZOOC/Network/Home/HomeService.swift
  ZOOC/ZOOC/Network/My/MyAPI.swift
  ZOOC/ZOOC/Network/My/MyService.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingService.swift
  ZOOC/ZOOC/Network/Record/RecordAPI.swift
  ZOOC/ZOOC/Network/Record/RecordService.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeCommentCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeNoticeViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyEditProfileView.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
Labels: 🐶 석우, ✨ Feature

#53 [Fix] #49 - 과제 전 최종 점검
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Application/SceneDelegate.swift
  ZOOC/ZOOC/Data/Home/APIModel/HomeCommentRequest.swift
  ZOOC/ZOOC/Network/Home/HomeAPI.swift
  ZOOC/ZOOC/Network/Home/HomeService.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeCommentCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift
Labels: 🐶 석우, ✨ Feature

#54 [Feat] #52 - 온보딩 오토레이아웃 수정
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteCompletedFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateCompletedView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingReInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingWelcomeView.swift
Labels: 🐰 윤선, 🔨 Fix

#58 [Fix] AlertViewController 배경색 및 라벨 색 수정 #56
  ZOOC/ZOOC/Presentation/Base/ZoocAlertViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyDeleteAccountAlertViewController.swift
Labels: 🐰 윤선, 🔨 Fix

#59 [Fix] #57 - UI관련 QA 반영하기
  ZOOC/ZOOC/Presentation/Home/Controller/HomeNoticeViewController.swift
  ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyPetCollectionFooterView.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift
Labels: 🐼 희재, 🔨 Fix

#65 [Feat] #62 - 상세보기 API 변동사항 반영
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/Base/APIConstants.swift
  ZOOC/ZOOC/Network/Home/HomeAPI.swift
  ZOOC/ZOOC/Network/Home/HomeService.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
Labels: 🐶 석우, ✨ Feature

#66 [Refactor] #64 - 홈뷰 코드 리팩토링
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Network/Record/RecordAPI.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveGridCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListWriterCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeCommentCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeGuideCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeMissionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomePetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeGuideViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeArchiveIndicatorView.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeDetailArchiveCommentTextField.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeView.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordCompleteViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift
Labels: 🐶 석우, ⚒️ Refactor

#67 [Refactor] #63 - 코드 수정
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Global/Extension/UIButton+.swift
  ZOOC/ZOOC/Global/Extension/UIImageView+.swift
  ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyPetCollectionFooterView.swift
  ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyRegisterPetTableFooterView.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyDeleteAccountSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilyCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyProfileSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MySettingSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyAppInformationViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyFamilyInviteViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyInviteCompleteViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyNoticeSettingViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyAppInformationView.swift
  ZOOC/ZOOC/Presentation/My/View/MyDeleteAccountAlertViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyNoticeSettingView.swift
  ZOOC/ZOOC/Presentation/My/View/MyRegisterPetView.swift
  ZOOC/ZOOC/Presentation/My/View/MyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingAgreementView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterPetView.swift
Labels: 🐼 희재, ⚒️ Refactor

#70 [Refactor] #68 - 상세보기뷰 리팩토링
  ZOOC/ZOOC/Global/Extension/UIImageView+.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeView.swift
Labels: 🐶 석우, ⚒️ Refactor

#72 [Refactor] #69 - 온보딩 코드 리펙토링
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingResult.swift
  ZOOC/ZOOC/Global/Extension/UIButton+.swift
  ZOOC/ZOOC/Global/Extension/UILabel+.swift
  ZOOC/ZOOC/Global/Extension/UIView+.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingAPI.swift
  ZOOC/ZOOC/Presentation/Base/BaseButton.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingAgreementTableHeaderView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingRegisterPetTableFooterView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingAgreementTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingChooseFamilyRoleViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingCompleteProfileViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingReInviteFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterProfileImageViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingWelcomeViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingAgreementView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingChooseFamilyRoleView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingCompleteProfileView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteCompletedFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingLoginView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateCompletedView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingReInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterPetView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterProfileImageView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingWelcomeView.swift
Labels: 🐼 희재, ⚒️ Refactor

#74 [Refactor] #73 - 마이페이지 코드 리펙토링
  ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyPetCollectionFooterView.swift
  ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyRegisterPetTableFooterView.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyProfileSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MySettingSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyNoticeSettingViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyDeleteAccountAlertViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyEditProfileView.swift
  ZOOC/ZOOC/Presentation/My/View/MyRegisterPetView.swift
  ZOOC/ZOOC/Presentation/My/View/MyView.swift
Labels: 🐼 희재, ⚒️ Refactor

#77 [Refactor] #75 - 온보딩뷰 리리팩토링
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingAgreementTableHeaderView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingRegisterPetTableFooterView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingAgreementTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingChooseFamilyRoleViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingCompleteProfileViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterProfileImageViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingWelcomeViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingAgreementView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingChooseFamilyRoleView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingCompleteProfileView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteCompletedFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingLoginView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateCompletedView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingReInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterPetView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterProfileImageView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingWelcomeView.swift
Labels: 🐼 희재, ⚒️ Refactor

#79 [Refactor] #78 - 마이페이지뷰 리리팩토링
  ZOOC/ZOOC/Data/My/Model/MyPetRegisterModel.swift
  ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyPetCollectionFooterView.swift
  ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyRegisterPetTableFooterView.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyAppInformationTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyDeleteAccountSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilyCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyProfileSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MySettingSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MySettingTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyAppInformationViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyAppInformationView.swift
  ZOOC/ZOOC/Presentation/My/View/MyDeleteAccountAlertViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyEditProfileView.swift
  ZOOC/ZOOC/Presentation/My/View/MyNoticeSettingView.swift
  ZOOC/ZOOC/Presentation/My/View/MyRegisterPetView.swift
  ZOOC/ZOOC/Presentation/My/View/MyView.swift
Labels: 🐼 희재, ⚒️ Refactor
