Repository TeamZOOC/ZOOC-iOS, pull requests merged in 2023-02, with the labels that each got.

#81 [Fix] #80 - 펫 등록 재사용 문제 해결하기
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/My/Model/MyPetRegisterViewModel.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingResult.swift
  ZOOC/ZOOC/Data/Onboarding/Model/OnboardingPetRegisterModel.swift
  ZOOC/ZOOC/Data/Onboarding/Model/OnboardingPetRegisterViewModel.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingAPI.swift
  ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyRegisterPetTableFooterView.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyRegisterPetView.swift
  ZOOC/ZOOC/Presentation/My/View/MyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingRegisterPetTableFooterView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingCompleteProfileViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
Labels: 🐼 희재, 🔨 Fix

#83 [Feat] #82 - 반려동물 등록하기 서버 통신
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingRegisterPetRequestDto.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingRegisterPetResult.swift
  ZOOC/ZOOC/Data/Onboarding/Model/OnboardingPetRegisterViewModel.swift
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/Base/APIConstants.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingAPI.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingService.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingAgreementTableHeaderView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/HeaderFooter/OnboardingRegisterPetTableFooterView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingAgreementTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingRegisterPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingChooseFamilyRoleViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingCompleteProfileViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingInviteFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateCompletedViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingParticipateViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingReInviteFamilyViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterProfileImageViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterPetView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterProfileImageView.swift
Labels: 🐼 희재, ✨ Feature

#88 [Feat] #84 - 카카오 소셜 로그인 앱에서 로그인 기능 구현 & 애플 소셜로그인 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Application/AppDelegate.swift
  ZOOC/ZOOC/Application/Info.plist
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingAppleSocailLoginRequestDto.swift
  ZOOC/ZOOC/Data/Onboarding/APIModel/OnboardingRegisterPetResult.swift
  ZOOC/ZOOC/Global/Constant/Image.swift
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingAPI.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingService.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingAgreementView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingChooseFamilyRoleView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingCompleteProfileView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteCompletedFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingLoginView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateCompletedView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingParticipateView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingReInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterPetView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterProfileImageView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingWelcomeView.swift
  ZOOC/ZOOC/Resource/Assets.xcassets/kakaoLogin.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/kakaoLogin.imageset/Group 48095819.png
  ZOOC/ZOOC/ZOOC.entitlements
Labels: 🐼 희재, ✨ Feature

#89 [Feat] #86 - 상세보기뷰 이모지 기능 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/Home/APIModel/HomeEmojiCommentRequest.swift
  ZOOC/ZOOC/Data/Home/Model/EmojiModel.swift
  ZOOC/ZOOC/Network/Home/HomeAPI.swift
  ZOOC/ZOOC/Network/Home/HomeService.swift
  ZOOC/ZOOC/Presentation/Home/Cell/EmojiCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/Home/View/EmojiBottomSheetViewController.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeDetailArchiveCommentView.swift
Labels: 🐶 석우, ✨ Feature

#92 [Refactor] #91 - 프로필 편집뷰 코드 리팩토링
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/My/APIModel/EditProfileRequest.swift
  ZOOC/ZOOC/Data/My/APIModel/MyResult.swift
  ZOOC/ZOOC/Network/My/MyAPI.swift
  ZOOC/ZOOC/Network/My/MyService.swift
  ZOOC/ZOOC/Presentation/Base/BaseTextField.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilyCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyFamilySectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyPetSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyProfileSectionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyAppInformationViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/My/View/GalleryAlertController.swift
  ZOOC/ZOOC/Presentation/My/View/MyAppInformationView.swift
  ZOOC/ZOOC/Presentation/My/View/MyEditProfileView.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingChooseFamilyRoleViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterProfileImageViewController.swift
Labels: 🐶 석우, ⚒️ Refactor

#93 [Feat] #90 - ImagePicker UX 개선
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterProfileImageViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
Labels: 🐶 석우, ✨ Feature
