Repository TeamZOOC/ZOOC-iOS, pull requests merged in 2023-05, with the labels that each got.

#135 [Chore] #132 - 기록하기/미션하기 뷰 개선
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/Record/APIModel/RecordMissionListModel.swift
  ZOOC/ZOOC/Data/Record/Model/RecordMissionModel.swift
  ZOOC/ZOOC/Data/Record/Model/RecordMissionViewModel.swift
  ZOOC/ZOOC/Data/Record/Model/RecordModel.swift
  ZOOC/ZOOC/Network/Record/RecordAPI.swift
  ZOOC/ZOOC/Network/Record/RecordService.swift
  ZOOC/ZOOC/Presentation/Base/ZoocAlertViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyAppInformationViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/Record/Cell/RecordMissionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/Cell/RecordRegisterCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/Cell/RecordRegisterFourCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordAlertViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordMissionViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordMissionView.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordRegisterView.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordView.swift
Labels: 🐼 희재, 🥢 Chore

#139 [Chore] #138 - 홈뷰 애니메이션 개선
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordMissionViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
Labels: 🐶 석우, 🥢 Chore

#143 [Chore] #142 - 마이페이지뷰 기기대응
  ZOOC/ZOOC/Application/AppDelegate.swift
  ZOOC/ZOOC/Presentation/My/Cell/HeaderFooterVIew/MyAppInformationHeaderView.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyAppInformationTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/View/MyNoticeSettingView.swift
  ZOOC/ZOOC/Presentation/My/View/MyRegisterPetView.swift
Labels: 🐼 희재, 🥢 Chore

#146 [Add] #145 - Sentry(Crashlytics)
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ZOOC/ZOOC/Application/AppDelegate.swift
  ZOOC/ZOOC/Application/SceneDelegate.swift
  ZOOC/ZOOC/Global/Error/AuthError.swift
  ZOOC/ZOOC/Network/Foundation/ZoocInterceptor.swift
Labels: 🐶 석우, ✨ Feature

#147 [Chore] #141 - 온보딩뷰 기기대응 및 코드 수정
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/UserDefaultsManager.swift
  ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveGuideViewController.swift
  ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeGuideViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingReInviteFamilyView.swift
  ZOOC/ZOOC/Presentation/Onboarding/View/OnboardingRegisterPetView.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift
Labels: 🥢 Chore

#150 [Feat] #148 - 게시물 삭제하기 기능 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Data/UserDefaultsManager.swift
  ZOOC/ZOOC/Global/Constant/EnternalURL.swift
  ZOOC/ZOOC/Network/Archive/ArchiveAPI.swift
  ZOOC/ZOOC/Network/Archive/ArchiveService.swift
  ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
Labels: 🐶 석우, ✨ Feature

#153 [Feat] #152 - 사진 전체화면 및 다운로드 기능 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Base/BaseViewController.swift
  ZOOC/ZOOC/Presentation/Base/ZoocImageController.swift
Labels: 🐶 석우, ✨ Feature

#155 [Chore] #154 - 온보딩 동의 뷰 수정
  ZOOC/ZOOC/Data/Onboarding/Model/OnboardingAgreementModel.swift
  ZOOC/ZOOC/Global/Extension/UILabel+.swift
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingAgreementTableViewCell.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingAgreementViewController.swift
  ZOOC/ZOOC/Resource/Assets.xcassets/checkbox.fill.imageset/Contents.json
  ZOOC/ZOOC/Resource/Assets.xcassets/checkbox.fill.imageset/checkbox.fill.pdf
  ZOOC/ZOOC/Resource/Assets.xcassets/checkbox.fill.imageset/checkbox.fill.png
Labels: 🐶 석우, 🥢 Chore

#157 [Fix] Hidden 값 오류 해결 #154
  ZOOC/ZOOC/Presentation/Onboarding/Cell/OnboardingAgreementTableViewCell.swift
Labels: 🐶 석우, 🔨 Fix

#158 [Set] #156 - [Set] 프로젝트 추가 세팅
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Application/AppDelegate.swift
  ZOOC/ZOOC/Application/Info.plist
  ZOOC/ZOOC/Global/Constant/Config.swift
  ZOOC/ZOOC/Network/Foundation/BaseTargetType.swift
  ZOOC/ZOOC/Network/Foundation/ZoocInterceptor.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingLoginViewController.swift
Labels: 🐶 석우, ⚙️ Setting
