Repository TeamZOOC/ZOOC-iOS, pull requests merged in 2023-06, with the labels that each got.

#159 [Chore] #144 - 기록하기 미션하기뷰 기기대응
  ZOOC/ZOOC/Presentation/Record/Cell/RecordMissionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/Cell/RecordRegisterCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/Cell/RecordRegisterFourCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordCompleteViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordMissionViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordMissionView.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordRegisterView.swift
  ZOOC/ZOOC/Presentation/Record/View/RecordView.swift
Labels: 🐼 희재, 🥢 Chore

#161 [Fix] #160 - 기획 QA - 기록하기 미션하기 관련 이슈 해결
  ZOOC/ZOOC/Data/Record/Model/RecordMissionViewModel.swift
  ZOOC/ZOOC/Data/Record/Model/RecordModel.swift
  ZOOC/ZOOC/Presentation/Home/View/HomeNoticeView.swift
  ZOOC/ZOOC/Presentation/My/Cell/MyRegisteredPetTableViewCell.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Record/Cell/RecordRegisterCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordMissionViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
Labels: 🐼 희재, ✨ Feature

#165 [Feat] #164 - 댓글 삭제하기 기능
  ZOOC/ZOOC/Data/Archive/APIModel/ArchiveResult.swift
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/Archive/ArchiveAPI.swift
  ZOOC/ZOOC/Network/Archive/ArchiveService.swift
  ZOOC/ZOOC/Presentation/Archive/Cell/ArchiveCommentCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift
Labels: 🐶 석우

#169 [Fix] #168 - [Fix] 디자인 QA 기록과 미션하기 화면 전환 알람창 반영
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Presentation/Archive/Controller/ArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Base/ZoocAlertViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditPetProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyViewController.swift
  ZOOC/ZOOC/Presentation/My/View/MyDeleteAccountAlertViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordMissionViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
Labels: 🐶 석우
