Repository TeamZOOC/ZOOC-iOS, pull requests merged in 2023-04, with the labels that each got.

#122 [Chore] #121 - 기록하기 관련 API 수정
  ZOOC/ZOOC/Data/Common/APIModel/RecordResult.swift
  ZOOC/ZOOC/Data/Home/APIModel/HomeDetailArchiveResult.swift
Labels: 🐼 희재, 🥢 Chore

#118 [Chore] #117 - 마이페이지 URL에 {familyId} 추가
  ZOOC/ZOOC/Global/Constant/URLs.swift
  ZOOC/ZOOC/Network/My/MyService.swift
Labels: 🐶 석우

#119 [Chore] #110 - FCM토큰 저장 API, 로그아웃 API 수정사항 반영
  ZOOC/ZOOC/Network/My/MyService.swift
  ZOOC/ZOOC/Network/Onboarding/OnboardingService.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordRegisterViewController.swift
Labels: 🐶 석우, 🥢 Chore

#127 [Feat] #124 - 상세보기 UI 변경 및 스와이프 기능 구현
  ZOOC/ZOOC.xcodeproj/project.pbxproj
  ZOOC/ZOOC/Global/Extension/UIViewController+.swift
  ZOOC/ZOOC/Presentation/Base/BaseViewController.swift
  ZOOC/ZOOC/Presentation/Home/Cell/EmojiCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveGridCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeArchiveListWriterCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeCommentCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeGuideCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeMissionCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomeNoticeTableViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Cell/HomePetCollectionViewCell.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeDetailArchiveViewController.swift
  ZOOC/ZOOC/Presentation/Home/Controller/HomeViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyEditProfileViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyNoticeSettingViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordMissionViewController.swift
  ZOOC/ZOOC/Presentation/Record/Controller/RecordViewController.swift
Labels: 🐶 석우, ✨ Feature

#126 [Feat] #125 - 카메라, 갤러리 접근 권한 설정
  ZOOC/ZOOC/Application/Info.plist
  ZOOC/ZOOC/Presentation/Base/BaseViewController.swift
  ZOOC/ZOOC/Presentation/My/Controller/MyRegisterPetViewController.swift
  ZOOC/ZOOC/Presentation/Onboarding/Controller/OnboardingRegisterPetViewController.swift
Labels: 🐼 희재, ✨ Feature
